{{- if .Values.union.cluster_resource_manager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustersync-resource
  namespace: {{ include "union-operator.namespace" . }}
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustersync-resource
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - rbac.authorization.k8s.io
    resources:
      - configmaps
      - namespaces
      - pods
      - resourcequotas
      - roles
      - rolebindings
      - secrets
      - services
      - serviceaccounts
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clustersync-resource
  labels:
    {{- include "union-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clustersync-resource
subjects:
  - kind: ServiceAccount
    name: clustersync-resource
    namespace: {{ include "union-operator.namespace" . }}

{{- end }}
